name: EffectArea
version: 0.0.1
main: jp.mydns.dyukusi.effectarea.EffectArea
commands:
   ea:
      description: Main RegenerationPoint base command.
      usage: /ea
   permissions:
      effectarea.areaconfigure:
          description: allow configure area command.