name: Notificator
version: 0.0.1
main: jp.mydns.dyukusi.notificator.Notificator
commands:
   noti:
      description: Notification command.
      usage: /noti pnews [News Message]
      permission: Notification.pnews
      permission-message: You don't have <permission>