name: Notificator
version: 0.0.1
main: jp.mydns.dyukusi.notificator.Notificator
commands:
   noti:
      description: Notification command.
      usage: /noti help
      permission-message: You don't have <permission>
permissions:
   notificator.add:
       description: Add new player news by paying charge.
   notificator.delete:
       description: Delete specific player message by selecting index.
      