name: MyPlugin
version: 0.0.1
main: jp.mydns.dyukusi.myplugin.MyPlugin
commands:
   mp:
      description: Main BiomeNotificator base command.
      usage: /mp demo or kastel
   s:
      description: Main BiomeNotificator base command.
      usage: /s something what you want to say