name: OfflineDepositor
version: 0.0.1
main: jp.mydns.dyukusi.offlinedepositor.OfflineDepositor
commands:
   od:
      description: can deposit and withdraw to offline players.
      usage: /od [deposit] [PlayerName] [Amount] [Reason]
      permission: OfflineDepositor.deposit
      permission-message: You don't have <permission>