#CraftLevel by Dyukusi( dyukusin@gmail.com )

#Minimum craft success rate( 0-100% )
minimum_success_rate: 15

#Default maximum craft success rate( 0-100% )
maximum_success_rate: 90

#How amount of success rate do you want to increase per one level after the level requirements?
increase_rate: 5

#When the level requirement of the item that isn't defined in this config is crafted, display error message. 
no_requirements_data_error: true

#Max craft level
max_craft_level: 50

#Message config
# §0:Black, §1:DarkBlue, §2:DarkGreen, §3:DarkAqua, §4:DarkRed, §5:Purple, §6:Gold,  §7:Gray, 
# §8:DarkGray, §9:Blue, §a:Green, §b:Aqua, §c:Red, §d:LightPurple, §e:Yellow,  §f:White
# ^n:NewLine
message:
  # ^c: material name
  Craft_Success: ^c§aのクラフトに成功した！ ^n§b< You succeeded to craft §f^c §b>
  
  # ^c: material name
  Craft_Failure: ^c§cのクラフトに失敗した！ ^n§b< You failed to craft §f^c §b>
  
  # ^g:GainExperience, ^n:CurrentExp, ^l:RequireExpForNextLevel, ^s:SuccessRate
  Craft_Gain_Experience: §a+^g  §fEXP： §6^c§f/^l  §eSuccess rate： §6^s§f
  
  # ^p:PlayerName, ^b:BeforeLevel, ^a:NewLevel
  Craft_Levelup: §f^p ： §gLv §6^b §f-> §6^a
    
  Error_Shift: §c現状ではクリックによるクラフトのみ対応しています。 ^n§b< Sorry, Crafting with click is only usable from now. >

#Next level experience requirement( level,exp )
next_level:
  - 1,50
  - 2,100
  - 3,200
  - 4,300
  - 5,400
  - 6,500
  - 7,600
  - 8,700
  - 9,800
  - 10,900
  - 11,1000
  - 12,1100
  - 13,1200
  - 14,1300
  - 15,1500
  - 16,1700
  - 17,1900
  - 18,2100
  - 19,2300
  - 20,2500
  - 21,2700
  - 22,2900
  - 23,3100
  - 24,3300
  - 25,3500
  - 26,3700
  - 27,3900
  - 28,4100
  - 29,4300
  - 30,4500
  - 31,4500
  - 32,4500
  - 33,4500
  - 34,4500
  - 35,4500
  - 36,4500
  - 37,4500
  - 38,4500
  - 39,4500
  - 40,4500
  - 41,4500
  - 42,4500
  - 43,4500
  - 44,4500
  - 45,4500
  - 46,4500
  - 47,4500
  - 48,4500
  - 49,4500
  - 50,4500
  - 51,4500
  - 52,4500
  - 53,4500
  - 54,4500
  - 55,4500
  - 56,4500

# Material data setting
# Format
#   Material, RequireLevel, ExperienceAsMaterial, Options
#
# Options( n = Integer )
#   MSR:n -> Max Success Rate. Not limited by default max success rate.
#   MIR:n -> Minimum Success Rate. Not limited by default minimum success rate.
#   FSR:n -> Fixed Success Rate. Not craft level based.
#   CEX:n -> Custom Craft Experience. Not material based.
#
# Example
#   - IRON_BLOCK,30,100,MSR:100,CEX:1000
#        Craft success rate starts to increase from level 30.
#        If IRON_BLOCK is used as material for crafting such as Anvil, base experience increases 100.
#        Max success rate is 100% regardless of default max success rate.
#        Base experience is 1000 regardless of material based experience.

material_info:
 - ACACIA_DOOR_ITEM,5,30,none
 - ACACIA_FENCE,1,0,none
 - ACACIA_FENCE_GATE,1,0,none
 - ACACIA_STAIRS,5,0,none
 - ACTIVATOR_RAIL,30,0,none
 - AIR,1,0,none
 - ANVIL,30,0,none
 - APPLE,0,150,none
 - ARMOR_STAND,20,0,none
 - ARROW,20,0,none
 - BAKED_POTATO,0,50,none
 - BANNER,15,50,FSR:100,CEX:0
 - BEACON,100,0,none
 - BED,5,0,none
 - BIRCH_DOOR_ITEM,5,30,none
 - BIRCH_FENCE,1,0,none
 - BIRCH_FENCE_GATE,1,0,none
 - BIRCH_WOOD_STAIRS,5,0,none
 - BLAZE_POWDER,35,300,none
 - BLAZE_ROD,0,750,none
 - BOAT,10,0,none
 - BONE,0,75,none
 - BOOK,15,50,none
 - BOOKSHELF,15,0,none
 - BOOK_AND_QUILL,15,5,none
 - BOW,15,300,none
 - BOWL,5,75,none
 - BREAD,10,0,none
 - BREWING_STAND,40,0,none
 - BREWING_STAND_ITEM,40,0,none
 - BRICK,20,35,none
 - BRICK_STAIRS,20,0,none
 - BROWN_MUSHROOM,0,100,none
 - BUCKET,20,200,none
 - CAKE,30,0,none
 - CARPET,20,0,none
 - CARROT,0,30,none
 - CARROT_ITEM,0,10,none
 - CARROT_STICK,1,0,none
 - CAULDRON,10,0,none
 - CAULDRON_ITEM,20,0,none
 - CHAINMAIL_BOOTS,20,0,none
 - CHAINMAIL_CHESTPLATE,20,0,none
 - CHAINMAIL_HELMET,20,0,none
 - CHAINMAIL_LEGGINGS,20,0,none
 - CHEST,5,150,none
 - CLAY,10,100,none
 - CLAY_BALL,0,50,none
 - CLAY_BRICK,0,75,none
 - COAL,50,50,FSR:100,CEX:0
 - COAL_BLOCK,10,100,FSR:100,CEX:0
 - COBBLESTONE,0,25,none
 - COBBLESTONE_STAIRS,10,0,none
 - COBBLE_WALL,15,0,none
 - COCOA,0,100,none
 - COMPASS,20,500,none
 - COOKED_RABBIT,0,75,none
 - COOKIE,15,0,none
 - DARK_OAK_DOOR_ITEM,5,30,none
 - DARK_OAK_FENCE,1,0,none
 - DARK_OAK_FENCE_GATE,1,0,none
 - DARK_OAK_STAIRS,5,0,none
 - DAYLIGHT_DETECTOR,40,0,none
 - DAYLIGHT_DETECTOR_INVERTED,40,0,none
 - DETECTOR_RAIL,30,0,none
 - DIAMOND,50,1500,FSR:100,CEX:0
 - DIAMOND_AXE,50,0,none
 - DIAMOND_BLOCK,50,100,FSR:100,CEX:0
 - DIAMOND_BOOTS,50,0,none
 - DIAMOND_CHESTPLATE,50,0,none
 - DIAMOND_HELMET,50,0,none
 - DIAMOND_HOE,50,0,none
 - DIAMOND_LEGGINGS,50,0,none
 - DIAMOND_PICKAXE,50,0,none
 - DIAMOND_SPADE,50,0,none
 - DIAMOND_SWORD,50,0,none
 - DIODE,20,0,none
 - DIRT,5,1,none
 - DISPENSER,30,1500,none
 - DOUBLE_PLANT,0,20,none
 - DROPPER,20,0,none
 - EGG,0,75,none
 - EMERALD,50,1000,FSR:100,CEX:0
 - EMERALD_BLOCK,50,100,FSR:100,CEX:0
 - EMPTY_MAP,15,30,none
 - ENCHANTMENT_TABLE,30,0,none
 - ENDER_CHEST,35,0,none
 - ENDER_PEARL,0,750,none
 - EXPLOSIVE_MINECART,35,0,none
 - EYE_OF_ENDER,50,2000,none
 - FEATHER,0,25,none
 - FENCE,5,0,none
 - FENCE_GATE,8,0,none
 - FERMENTED_SPIDER_EYE,30,0,none
 - FIREBALL,40,200,none
 - FIREWORK,35,0,none
 - FIREWORK_CHARGE,25,0,none
 - FISHING_ROD,1,50,none
 - FLINT,0,100,none
 - FLINT_AND_STEEL,20,0,none
 - FLOWER_POT_ITEM,11,0,none
 - FURNACE,5,200,none
 - GLASS,20,100,none
 - GLASS_BOTTLE,25,50,none
 - GLOWSTONE,30,500,none
 - GLOWSTONE_DUST,25,100,none
 - GOLDEN_APPLE,50,0,none
 - GOLDEN_CARROT,30,0,none
 - GOLD_AXE,25,0,none
 - GOLD_BLOCK,30,0,FSR:100,CEX:0
 - GOLD_BOOTS,15,0,none
 - GOLD_CHESTPLATE,15,0,none
 - GOLD_HELMET,15,0,none
 - GOLD_HOE,25,0,none
 - GOLD_INGOT,20,300,FSR:100,CEX:0
 - GOLD_LEGGINGS,15,0,none
 - GOLD_NUGGET,100,50,none
 - GOLD_PICKAXE,25,0,none
 - GOLD_PLATE,20,0,none
 - GOLD_SPADE,25,0,none
 - GOLD_SWORD,25,0,none
 - GRAVEL,0,10,none
 - HARD_CLAY,0,15,none
 - HAY_BLOCK,15,100,FSR:100,CEX:0
 - HOPPER,25,1000,none
 - HOPPER_MINECART,30,0,none
 - INK_SACK,10,100,FSR:100,CEX:0
 - IRON_AXE,25,0,none
 - IRON_BLOCK,30,0,FSR:100,CEX:0
 - IRON_BOOTS,25,0,none
 - IRON_CHESTPLATE,25,0,none
 - IRON_DOOR,20,0,none
 - IRON_DOOR_BLOCK,5,30,none
 - IRON_FENCE,20,0,none
 - IRON_HELMET,25,0,none
 - IRON_HOE,25,0,none
 - IRON_INGOT,25,250,FSR:100,CEX:0
 - IRON_LEGGINGS,25,0,none
 - IRON_PICKAXE,25,0,none
 - IRON_PLATE,25,0,none
 - IRON_SPADE,25,0,none
 - IRON_SWORD,25,0,none
 - IRON_TRAPDOOR,20,0,none
 - ITEM_FRAME,25,0,none
 - JACK_O_LANTERN,15,0,none
 - JUKEBOX,30,0,none
 - JUNGLE_DOOR_ITEM,5,30,none
 - JUNGLE_FENCE,1,0,none
 - JUNGLE_FENCE_GATE,1,0,none
 - JUNGLE_WOOD_STAIRS,5,0,none
 - LADDER,10,0,none
 - LAPIS_BLOCK,10,0,FSR:100,CEX:0
 - LEASH,20,0,none
 - LEATHER,10,100,none
 - LEATHER_BOOTS,5,0,none
 - LEATHER_CHESTPLATE,5,0,none
 - LEATHER_HELMET,5,0,none
 - LEATHER_LEGGINGS,5,0,none
 - LEVER,10,0,none
 - LOG,0,50,none
 - LOG_2,0,50,none
 - MAGMA_CREAM,40,0,none
 - MAP,20,150,FSR:100,CEX:0
 - MELON,0,25,none
 - MELON_BLOCK,50,0,none
 - MELON_SEEDS,25,0,FSR:30
 - MILK_BUCKET,0,100,none
 - MINECART,30,1250,none
 - MOSSY_COBBLESTONE,10,25,none
 - MUSHROOM_SOUP,5,0,none
 - NETHER_BRICK,10,100,none
 - NETHER_BRICK_ITEM,0,100,none
 - NETHER_BRICK_STAIRS,30,0,none
 - NETHER_FENCE,30,0,none
 - NETHER_STAR,0,1000,none
 - NOTE_BLOCK,15,0,none
 - OBSIDIAN,0,750,none
 - PAINTING,20,0,none
 - PAPER,15,15,none
 - PISTON_BASE,20,100,none
 - PISTON_STICKY_BASE,25,0,none
 - POWERED_MINECART,35,0,none
 - POWERED_RAIL,30,0,none
 - PRISMARINE,30,80,none
 - PRISMARINE_CRYSTALS,0,80,none
 - PRISMARINE_SHARD,0,80,none
 - PUMPKIN,0,100,none
 - PUMPKIN_PIE,20,0,none
 - PUMPKIN_SEEDS,25,0,FSR:30
 - QUARTZ,0,350,none
 - QUARTZ_BLOCK,10,200,none
 - QUARTZ_STAIRS,30,0,none
 - RABBIT_HIDE,0,40,none
 - RABBIT_STEW,10,0,none
 - RAILS,30,0,none
 - REDSTONE,50,100,FSR:100,CEX:0
 - REDSTONE_BLOCK,10,100,FSR:100,CEX:0
 - REDSTONE_COMPARATOR,30,0,none
 - REDSTONE_LAMP_OFF,30,0,none
 - REDSTONE_TORCH_OFF,25,150,none
 - REDSTONE_TORCH_ON,25,150,none
 - RED_MUSHROOM,0,100,none
 - RED_ROSE,0,11,none
 - RED_SANDSTONE,10,50,none
 - RED_SANDSTONE_STAIRS,20,0,none
 - SAND,10,15,none
 - SANDSTONE,10,25,none
 - SANDSTONE_STAIRS,20,0,none
 - SEA_LANTERN,30,0,none
 - SHEARS,20,0,none
 - SIGN,3,0,none
 - SLIME_BALL,50,100,FSR:100,CEX:0
 - SLIME_BLOCK,20,100,FSR:100,CEX:0
 - SMOOTH_BRICK,15,15,none
 - SMOOTH_STAIRS,15,0,none
 - SNOW_BALL,0,25,FSR:100,CEX:0
 - SNOW_BLOCK,10,0,FSR:100,CEX:0
 - SPECKLED_MELON,40,0,none
 - SPIDER_EYE,0,100,none
 - SPRUCE_DOOR_ITEM,5,30,none
 - SPRUCE_FENCE,1,0,none
 - SPRUCE_FENCE_GATE,1,0,none
 - SPRUCE_WOOD_STAIRS,5,0,none
 - STAINED_CLAY,20,0,none
 - STAINED_GLASS,20,25,none
 - STAINED_GLASS_PANE,20,0,none
 - STANDING_BANNER,15,0,none
 - STEP,10,15,none
 - STICK,1,10,none
 - STONE,15,50,none
 - STONE_AXE,10,0,none
 - STONE_BUTTON,10,0,none
 - STONE_HOE,10,0,none
 - STONE_PICKAXE,10,0,none
 - STONE_PLATE,15,50,none
 - STONE_SLAB2,15,50,none
 - STONE_SPADE,10,0,none
 - STONE_SWORD,10,0,none
 - STORAGE_MINECART,35,0,none
 - STRING,0,50,none
 - SUGAR,25,50,none
 - SUGAR_CANE,0,75,none
 - SULPHUR,0,100,none
 - THIN_GLASS,20,0,none
 - TNT,50,1000,none
 - TORCH,5,60,none
 - TRAPPED_CHEST,20,0,none
 - TRAP_DOOR,5,0,none
 - TRIPWIRE_HOOK,25,300,none
 - VINE,0,100,none
 - WATCH,20,200,none
 - WHEAT,50,50,FSR:100,CEX:0
 - WOOD,1,25,none
 - WOODEN_DOOR,5,30,none
 - WOOD_AXE,1,0,none
 - WOOD_BUTTON,5,0,none
 - WOOD_DOOR,1,0,none
 - WOOD_HOE,1,0,none
 - WOOD_PICKAXE,1,0,none
 - WOOD_PLATE,10,25,none
 - WOOD_SPADE,1,0,none
 - WOOD_STAIRS,5,0,none
 - WOOD_STEP,5,5,none
 - WOOD_SWORD,1,0,none
 - WOOL,10,75,none
 - WORKBENCH,1,0,none
 - WRITTEN_BOOK,20,0,none
 - YELLOW_FLOWER,0,11,none
