name: CraftLevel
version: 0.0.1
main: jp.mydns.dyukusi.craftlevel.CraftLevel
commands:
   cl:
      description: Main CraftLevel base command.
      usage: /cl status PlayerName(optional)
permissions:
   craftlevel.status:
       description: Display current craft level and craft experience.
   craftlevel.set:
       description: set craft level and experience.
