name: CraftLevel
version: 0.0.1
main: jp.mydns.dyukusi.craftlevel.CraftLevel
commands:
   cl:
      description: set level or exp command.
      usage: /cl set [level or exp] [PlayerName] [Amount]
      permission: CraftLevel.set
      permission-message: You don't have <permission>