name: AreaNotificator
version: 0.0.1
main: jp.mydns.dyukusi.areanotificator.AreaNotificator
commands:
   an:
      description: Main AreaNotificator base command.
      usage: /an
permissions:
   areanotificatior.create:
       description: allow create new custom area command.